name: Main

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE:  ${{ github.repository }}

jobs:
  test_build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Define image meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
        tags: |
          type=raw,value=sha-${{ github.sha }}
        labels: |
          org.opencontainers.image.authors=epoc
          org.opencontainers.image.vendor=three.consulting
        flavor: |
          latest=true

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        no-cache: false
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
