name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

env:
  REGISTRY: ghcr.io
  IMAGE:  ${{ github.repository }}

jobs:
  test_build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Define image meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
        tags: |
          type=raw,value=${{ github.event.pull_request.head.sha }}
          type=raw,value=sha-${{ github.sha }}
        labels: |
          org.opencontainers.image.authors=epoc
          org.opencontainers.image.vendor=three.consulting
        flavor: |
          latest=false

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        no-cache: false
        push: false
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
